branches:
  only:
    - master

os: Windows Server 2012

clone_folder: c:\pvpgn

install:
  - cmd: cd c:\
  - cmd: appveyor DownloadFile https://github.com/Danteoriginal/pvpgn-magic-builder/archive/master.zip
  - cmd: 7z.exe x master.zip >nul
  - cmd: ren pvpgn-magic-builder-master builder
  - cmd: mkdir c:\builder\source\
  - cmd: xcopy /E /R /K /Y /Q "c:\pvpgn" "c:\builder\source\"
  - cmd: cd c:\builder\
  - cmd: appveyor DownloadFile https://www.dropbox.com/s/bij8kmxp4wm41jx/magic.ps1?dl=1

before_build:
  - cmd: set PVPGN_PLAIN_ZIP=pvpgn_%APPVEYOR_BUILD_VERSION%_plain.zip
  - cmd: set PVPGN_MYSQL_ZIP=pvpgn_%APPVEYOR_BUILD_VERSION%_mysql.zip
  - cmd: set PVPGN_PGSQL_ZIP=pvpgn_%APPVEYOR_BUILD_VERSION%_pgsql.zip
  - cmd: set PVPGN_SQLITE_ZIP=pvpgn_%APPVEYOR_BUILD_VERSION%_sqlite.zip
  - cmd: set PVPGN_ODBC_ZIP=pvpgn_%APPVEYOR_BUILD_VERSION%_odbc.zip

build_script:

  # build gui and console for each storage type
  # params:
  #  1. automatic build flag
  #  2. visual studio version
  #  3. console or gui
  #  4. storage type
  #  5. with or without lua

  # plain
  - cmd: build_pvpgn.bat auto 7 2 1 y
  - cmd: move release\*.exe
  - cmd: build_pvpgn.bat auto 7 1 1 y
  - cmd: move /Y *.exe release
  - cmd: 7z.exe a %PVPGN_PLAIN_ZIP% .\release\*
  
  # mysql
  - cmd: build_pvpgn.bat auto 7 2 2 y
  - cmd: move release\*.exe
  - cmd: build_pvpgn.bat auto 7 1 2 y
  - cmd: move /Y *.exe release
  - cmd: 7z.exe a %PVPGN_MYSQL_ZIP% .\release\*

  # pgsql
  - cmd: build_pvpgn.bat auto 7 2 3 y
  - cmd: move release\*.exe
  - cmd: build_pvpgn.bat auto 7 1 3 y
  - cmd: move /Y *.exe release
  - cmd: 7z.exe a %PVPGN_PGSQL_ZIP% .\release\*

  # sqlite
  - cmd: build_pvpgn.bat auto 7 2 4 y
  - cmd: move release\*.exe
  - cmd: build_pvpgn.bat auto 7 1 4 y
  - cmd: move /Y *.exe release
  - cmd: 7z.exe a %PVPGN_SQLITE_ZIP% .\release\*

  # odbc
  - cmd: build_pvpgn.bat auto 7 2 5 y
  - cmd: move release\*.exe
  - cmd: build_pvpgn.bat auto 7 1 5 y
  - cmd: move /Y *.exe release
  - cmd: 7z.exe a %PVPGN_ODBC_ZIP% .\release\*

after_build:
    - PowerShell .\magic.ps1 -dir "%APPVEYOR_BUILD_VERSION%" -file "%PVPGN_PLAIN_ZIP%"
    - PowerShell .\magic.ps1 -dir "%APPVEYOR_BUILD_VERSION%" -file "%PVPGN_MYSQL_ZIP%"
    - PowerShell .\magic.ps1 -dir "%APPVEYOR_BUILD_VERSION%" -file "%PVPGN_PGSQL_ZIP%"
    - PowerShell .\magic.ps1 -dir "%APPVEYOR_BUILD_VERSION%" -file "%PVPGN_SQLITE_ZIP%"
    - PowerShell .\magic.ps1 -dir "%APPVEYOR_BUILD_VERSION%" -file "%PVPGN_ODBC_ZIP%"
  
test:
  assemblies:
    - '**\src\bnetd\Release\bnetd.exe'
